import { useState } from "react";
import { Globe, Sparkles, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";

export default function WebsiteGenerator() {
  const [prompt, setPrompt] = useState("");
  const [generatedHtml, setGeneratedHtml] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const generateWebsite = () => {
    if (!prompt.trim()) {
      toast.error("Please enter a prompt");
      return;
    }

    setIsLoading(true);

    setTimeout(() => {
      const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${prompt}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            line-height: 1.6;
            color: #333;
        }
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 4rem 2rem;
            text-align: center;
        }
        h1 { font-size: 2.5rem; margin-bottom: 1rem; }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 3rem 2rem;
        }
        .features {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
            margin: 2rem 0;
        }
        .feature {
            background: #f8f9fa;
            padding: 2rem;
            border-radius: 8px;
            text-align: center;
        }
        .feature h3 { color: #667eea; margin-bottom: 1rem; }
    </style>
</head>
<body>
    <header>
        <h1>${prompt}</h1>
        <p>Generated by AcZone AI</p>
    </header>
    
    <div class="container">
        <section class="features">
            <div class="feature">
                <h3>Feature One</h3>
                <p>This is a placeholder for your first feature. Customize it as needed.</p>
            </div>
            <div class="feature">
                <h3>Feature Two</h3>
                <p>This is a placeholder for your second feature. Customize it as needed.</p>
            </div>
            <div class="feature">
                <h3>Feature Three</h3>
                <p>This is a placeholder for your third feature. Customize it as needed.</p>
            </div>
        </section>
    </div>
</body>
</html>`;

      setGeneratedHtml(html);
      setIsLoading(false);
      toast.success("Website generated successfully!");
    }, 2000);
  };

  const downloadHtml = () => {
    const blob = new Blob([generatedHtml], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "generated-website.html";
    a.click();
    toast.success("Website downloaded!");
  };

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Website Generator</h1>
        <p className="text-muted-foreground mt-1">
          Generate complete websites from prompts
        </p>
      </div>

      {/* Input */}
      <Card className="p-6 space-y-4">
        <Textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe the website you want to generate..."
          rows={3}
        />
        <div className="flex gap-2">
          <Button onClick={generateWebsite} disabled={isLoading}>
            {isLoading ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Website
              </>
            )}
          </Button>
          {generatedHtml && (
            <Button variant="outline" onClick={downloadHtml}>
              <Download className="w-4 h-4 mr-2" />
              Download HTML
            </Button>
          )}
        </div>
      </Card>

      {/* Preview */}
      {generatedHtml && (
        <Card className="p-6">
          <h3 className="font-semibold mb-4">Website Preview</h3>
          <div className="border border-border rounded-lg overflow-hidden">
            <iframe
              srcDoc={generatedHtml}
              className="w-full h-[600px] bg-white"
              title="Website Preview"
            />
          </div>
        </Card>
      )}

      {/* Empty State */}
      {!generatedHtml && !isLoading && (
        <Card className="p-12 text-center">
          <Globe className="w-16 h-16 mx-auto text-muted-foreground mb-4" />
          <h3 className="text-lg font-semibold mb-2">No website generated yet</h3>
          <p className="text-muted-foreground">
            Enter a prompt above to start creating websites
          </p>
        </Card>
      )}
    </div>
  );
}
